{
 "title": "Main",
 "description": "Main IO Metering View",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vpsa",
    "label": "VPSA",
    "query": "SHOW TAG VALUES FROM \"io\" WITH KEY = \"vpsa\""
   },
   {
    "name": "dev_name",
    "label": "Device Type",
    "query": "SHOW TAG VALUES FROM \"io\" WITH KEY = \"dev_name\" WHERE \"vpsa\" =~ /$vpsa/"
   },
   {
    "name": "dev_server_name",
    "label": "Server Name",
    "query": "SHOW TAG VALUES FROM \"io\" WITH KEY = \"dev_server_name\" WHERE \"vpsa\" =~ /$vpsa/ AND \"dev_name\" =~ /$dev_name/"
   },
   {
    "name": "bucket_name",
    "label": "IO Type",
    "query": "SHOW TAG VALUES FROM \"io\" WITH KEY = \"bucket_name\" WHERE \"vpsa\" =~ /$vpsa/ AND \"dev_name\" =~ /$dev_name/"
   },
   {
    "name": "dev_ext_name",
    "label": "Device Name",
    "query": "SHOW TAG VALUES FROM \"io\" WITH KEY = \"dev_ext_name\" WHERE \"vpsa\" =~ /$vpsa/ AND \"dev_name\" =~ /$dev_name/ AND \"dev_server_name\" =~ /$dev_server_name/ AND bucket_name =~ /$bucket_name/"
   }
  ]
 },
 "panels": [
  { "title": "Individual Device Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IOPS (Stacked By IO Type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "dev_server_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "select": [
      [
       { "params": [ "iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iops" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
      { "condition": "AND", "key": "dev_name", "operator": "=~", "value": "/^$dev_name$/" },
      { "condition": "AND", "key": "dev_server_name", "operator": "=~", "value": "/^$dev_server_name$/" },
      { "condition": "AND", "key": "bucket_name", "operator": "=~", "value": "/^$bucket_name$/" },
      { "condition": "AND", "key": "dev_ext_name", "operator": "=~", "value": "/^$dev_ext_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "dev_server_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "select": [
      [
       { "params": [ "latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "latency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
      { "condition": "AND", "key": "dev_name", "operator": "=~", "value": "/^$dev_name$/" },
      { "condition": "AND", "key": "dev_server_name", "operator": "=~", "value": "/^$dev_server_name$/" },
      { "condition": "AND", "key": "bucket_name", "operator": "=~", "value": "/^$bucket_name$/" },
      { "condition": "AND", "key": "dev_ext_name", "operator": "=~", "value": "/^$dev_ext_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput (Stacked By IO Type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dev_server_name" ], "type": "tag" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "throughput" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
      { "condition": "AND", "key": "dev_name", "operator": "=~", "value": "/^$dev_name$/" },
      { "condition": "AND", "key": "dev_server_name", "operator": "=~", "value": "/^$dev_server_name$/" },
      { "condition": "AND", "key": "bucket_name", "operator": "=~", "value": "/^$bucket_name$/" },
      { "condition": "AND", "key": "dev_ext_name", "operator": "=~", "value": "/^$dev_ext_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Individual Device Meta Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Average IO Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "query": "SELECT mean(\"bps\")/mean(\"iops\") AS \"io_size\" FROM \"io\" WHERE (\"vpsa\" =~ /^$vpsa$/ AND \"dev_name\" =~ /^$dev_name$/ AND \"dev_server_name\" =~ /^$dev_server_name$/ AND \"bucket_name\" =~ /^$bucket_name$/ AND \"dev_ext_name\" =~ /^$dev_ext_name$/) AND $timeFilter GROUP BY time($__interval), \"bucket_name\" fill(null)",
     "select": [
      [
       { "params": [ "max_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "latency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
      { "condition": "AND", "key": "dev_name", "operator": "=~", "value": "/^$dev_name$/" },
      { "condition": "AND", "key": "dev_server_name", "operator": "=~", "value": "/^$dev_server_name$/" },
      { "condition": "AND", "key": "bucket_name", "operator": "=~", "value": "/^$bucket_name$/" },
      { "condition": "AND", "key": "dev_ext_name", "operator": "=~", "value": "/^$dev_ext_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "select": [
      [
       { "params": [ "max_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "latency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
      { "condition": "AND", "key": "dev_name", "operator": "=~", "value": "/^$dev_name$/" },
      { "condition": "AND", "key": "dev_server_name", "operator": "=~", "value": "/^$dev_server_name$/" },
      { "condition": "AND", "key": "bucket_name", "operator": "=~", "value": "/^$bucket_name$/" },
      { "condition": "AND", "key": "dev_ext_name", "operator": "=~", "value": "/^$dev_ext_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Active IOs (Stacked By IO Type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "dev_server_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "select": [
      [
       { "params": [ "active_ios" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active_io" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
      { "condition": "AND", "key": "dev_name", "operator": "=~", "value": "/^$dev_name$/" },
      { "condition": "AND", "key": "dev_server_name", "operator": "=~", "value": "/^$dev_server_name$/" },
      { "condition": "AND", "key": "bucket_name", "operator": "=~", "value": "/^$bucket_name$/" },
      { "condition": "AND", "key": "dev_ext_name", "operator": "=~", "value": "/^$dev_ext_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Combined Latency Statistics (View Latency For All Devices of a Device Type on a Single Graph - Select Device Type on Top - e.g. \"DRIVE\", or \"RAID-GROUP\" + Server Type \"CACHE\")",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bucket_name" ], "type": "tag" },
        { "params": [ "dev_ext_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "io",
       "select": [
        [
         { "params": [ "latency_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "latency" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
        { "condition": "AND", "key": "dev_name", "operator": "=~", "value": "/^$dev_name$/" },
        { "condition": "AND", "key": "dev_server_name", "operator": "=~", "value": "/^$dev_server_name$/" },
        { "condition": "AND", "key": "bucket_name", "operator": "=~", "value": "/^$bucket_name$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Combined IOPS Statistics (View IOPS For All Devices of a Device Type on a Single Graph - Select Device Type on Top - e.g. \"DRIVE\", or \"RAID-GROUP\" + Server Type \"CACHE\")",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bucket_name" ], "type": "tag" },
        { "params": [ "dev_ext_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "io",
       "select": [
        [
         { "params": [ "iops" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "iops" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
        { "condition": "AND", "key": "dev_name", "operator": "=~", "value": "/^$dev_name$/" },
        { "condition": "AND", "key": "dev_server_name", "operator": "=~", "value": "/^$dev_server_name$/" },
        { "condition": "AND", "key": "bucket_name", "operator": "=~", "value": "/^$bucket_name$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Combined Throughput Statistics (View Throughput For All Devices of a Device Type on a Single Graph - Select Device Type on Top - e.g. \"DRIVE\", or \"RAID-GROUP\" + Server Type \"CACHE\")",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bucket_name" ], "type": "tag" },
        { "params": [ "dev_ext_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "io",
       "select": [
        [
         { "params": [ "bps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "throughput" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
        { "condition": "AND", "key": "dev_name", "operator": "=~", "value": "/^$dev_name$/" },
        { "condition": "AND", "key": "dev_server_name", "operator": "=~", "value": "/^$dev_server_name$/" },
        { "condition": "AND", "key": "bucket_name", "operator": "=~", "value": "/^$bucket_name$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Cumulative Pool Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Pool Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "query": "SELECT sum(\"bps\") AS \"throughput\" FROM \"io\" WHERE \"vpsa\" =~ /^$vpsa$/ AND \"dev_name\" = 'POOL' AND $timeFilter GROUP BY time($__interval), \"bucket_name\" fill(null)",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "throughput" ], "type": "alias" }
      ],
      [
       { "params": [ "iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iops" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dev_name", "operator": "=", "value": "POOL" }
     ]
    }
   ]
  },
  {
   "title": "Total Pool IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "query": "SELECT sum(\"iops\") AS \"iops\" FROM \"io\" WHERE \"vpsa\" =~ /^$vpsa$/ AND \"dev_name\" = 'POOL' AND $timeFilter GROUP BY time($__interval), \"bucket_name\" fill(null)",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "throughput" ], "type": "alias" }
      ],
      [
       { "params": [ "iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iops" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dev_name", "operator": "=", "value": "VOLUME" }
     ]
    }
   ]
  },
  { "title": "Cumulative Volume Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Total Volume Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "query": "SELECT sum(\"bps\") AS \"throughput\" FROM \"io\" WHERE \"vpsa\" =~ /^$vpsa$/ AND \"dev_name\" = 'VOLUME' AND $timeFilter GROUP BY time($__interval), \"bucket_name\" fill(null)",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "throughput" ], "type": "alias" }
      ],
      [
       { "params": [ "iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iops" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dev_name", "operator": "=", "value": "POOL" }
     ]
    }
   ]
  },
  {
   "title": "Total Volume IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "query": "SELECT sum(\"iops\") AS \"iops\" FROM \"io\" WHERE \"vpsa\" =~ /^$vpsa$/ AND \"dev_name\" = 'VOLUME' AND $timeFilter GROUP BY time($__interval), \"bucket_name\" fill(null)",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "throughput" ], "type": "alias" }
      ],
      [
       { "params": [ "iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iops" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "dev_name", "operator": "=", "value": "VOLUME" }
     ]
    }
   ]
  },
  { "title": "System Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"cpu_iowait\") AS \"iowait\", mean(\"cpu_system\") AS \"system\", mean(\"cpu_user\") AS \"user\", mean(\"cpu_system\") + mean(\"cpu_user\") AS \"total_without_iowait\" FROM \"system\" WHERE \"vpsa\" =~ /^$vpsa$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory (Stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "mem_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "allocated" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" }
     ]
    }
   ]
  },
  { "title": "Cache Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Cache IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "select": [
      [
       { "params": [ "iops" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "iops" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
      { "condition": "AND", "key": "dev_name", "operator": "=", "value": "RAID-GROUP" },
      { "condition": "AND", "key": "dev_server_name", "operator": "=", "value": "CACHE" }
     ]
    }
   ]
  },
  {
   "title": "Cache Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "select": [
      [
       { "params": [ "latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "latency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
      { "condition": "AND", "key": "dev_name", "operator": "=", "value": "RAID-GROUP" },
      { "condition": "AND", "key": "dev_server_name", "operator": "=", "value": "CACHE" }
     ]
    }
   ]
  },
  {
   "title": "Cache Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucket_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "throughput" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vpsa", "operator": "=~", "value": "/^$vpsa$/" },
      { "condition": "AND", "key": "dev_name", "operator": "=", "value": "RAID-GROUP" },
      { "condition": "AND", "key": "dev_server_name", "operator": "=", "value": "CACHE" }
     ]
    }
   ]
  },
  { "title": "Cache Meta Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"data_read_hit\") AS \"read_hit_rate\", mean(\"data_write_hit\") AS \"write_hit_rate\" FROM \"zcache\" WHERE \"vpsa\" =~ /^$vpsa$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mem_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "allocated" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"meta_clean\") + mean(\"meta_dirty\") AS \"metadata\", mean(\"data_clean\") AS \"clean\", mean(\"data_dirty\") AS \"dirty\" FROM \"zcache\" WHERE \"vpsa\" =~ /^$vpsa$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mem_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "allocated" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}